"""
This is a setup.py script generated by py2applet.

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['unlocked.txt', 'options.txt', 'images', 'music',
              'custom_levels', 'levels', 'fonts']
OPTIONS = {'iconfile': 'tank_game.icns',
           'excludes': ['numpy', 'scipy', 'matplotlib'],
           'includes': ['pygame'],
           'argv_emulation': True,
           'plist': {
               'CFBundleName': 'Tank Game',
               'CFBundleVersion': '1.1',
               'NSHumanReadableCopyright': '© Guillaume Coiffier & '
               'Florimond Manca, 2016'}}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    data_files=DATA_FILES,
    setup_requires=['py2app'],
)
